name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Run Tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/Lab7
        python -m doctest Lab7/consultation.py
        python -m unittest Lab7/test_consultation.py